/**
 * Avatar Library v4 — ULTRA HD EDITION
 *
 * Sources (All High-Resolution):
 * - Games: Steam Library Heroes (1920x620 HD) + Official HD Assets
 * - Pokémon: PokeAPI Official Artwork (475x475 HD)
 * - Tech: SimpleIcons SVG (Vector Quality) + Official Brand CDNs
 * - Emojis: Apple Emoji High-Res (320px HD)
 * - AI: DiceBear HD (512px render)
 */

export type AvatarCategory = 'games' | 'budpoks' | 'logos' | 'animated' | 'realistic';

export interface AvatarOption {
  id: string;
  name: string;
  category: AvatarCategory;
  url: string;
  fallbackUrl?: string; // Fallback if primary URL fails
  isAnimated?: boolean;
  desc?: string;
}

// ===== GAME ART — Steam Library Heroes (1920x620 HD) with Fallback =====
// Primary: library_hero.jpg (widescreen 1920x620 HD)
// Fallback: header.jpg (460x215, if primary fails)
const GAME_AVATARS: AvatarOption[] = [
  // AAA Games (Ultra HD Quality with fallback)
  {
    id: 'game-cs2',
    name: 'Counter-Strike 2',
    category: 'games',
    url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/730/library_hero.jpg',
    fallbackUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/730/header.jpg',
    desc: 'FPS Competitive',
  },
  {
    id: 'game-dota2',
    name: 'Dota 2',
    category: 'games',
    url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/570/library_hero.jpg',
    fallbackUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/570/header.jpg',
    desc: 'MOBA Strategy',
  },
  {
    id: 'game-gtav',
    name: 'GTA V',
    category: 'games',
    url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/271590/library_hero.jpg',
    fallbackUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/271590/header.jpg',
    desc: 'Open World Action',
  },
  {
    id: 'game-elden',
    name: 'Elden Ring',
    category: 'games',
    url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/library_hero.jpg',
    fallbackUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1245620/header.jpg',
    desc: 'Dark Fantasy RPG',
  },
  {
    id: 'game-cyberpunk',
    name: 'Cyberpunk 2077',
    category: 'games',
    url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/library_hero.jpg',
    fallbackUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1091500/header.jpg',
    desc: 'Sci-Fi Open World',
  },
  {
    id: 'game-apex',
    name: 'Apex Legends',
    category: 'games',
    url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1172470/library_hero.jpg',
    fallbackUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1172470/header.jpg',
    desc: 'Battle Royale',
  },
  {
    id: 'game-pubg',
    name: 'PUBG',
    category: 'games',
    url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/578080/library_hero.jpg',
    fallbackUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/578080/header.jpg',
    desc: 'Battle Royale',
  },
  {
    id: 'game-rdr2',
    name: 'Red Dead Redemption 2',
    category: 'games',
    url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/library_hero.jpg',
    fallbackUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1174180/header.jpg',
    desc: 'Western Adventure',
  },
  {
    id: 'game-witcher3',
    name: 'The Witcher 3',
    category: 'games',
    url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/292030/library_hero.jpg',
    fallbackUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/292030/header.jpg',
    desc: 'Fantasy RPG',
  },
  {
    id: 'game-terraria',
    name: 'Terraria',
    category: 'games',
    url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/105600/library_hero.jpg',
    fallbackUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/105600/header.jpg',
    desc: 'Sandbox Adventure',
  },
  {
    id: 'game-rust',
    name: 'Rust',
    category: 'games',
    url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/252490/library_hero.jpg',
    fallbackUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/252490/header.jpg',
    desc: 'Survival Multiplayer',
  },
  {
    id: 'game-amongus',
    name: 'Among Us',
    category: 'games',
    url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/945360/library_hero.jpg',
    fallbackUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/945360/header.jpg',
    desc: 'Social Deduction',
  },
  {
    id: 'game-hades',
    name: 'Hades',
    category: 'games',
    url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1145360/library_hero.jpg',
    fallbackUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1145360/header.jpg',
    desc: 'Roguelike Action',
  },
  {
    id: 'game-portal2',
    name: 'Portal 2',
    category: 'games',
    url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/620/library_hero.jpg',
    fallbackUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/620/header.jpg',
    desc: 'Puzzle FPS',
  },
  {
    id: 'game-tf2',
    name: 'Team Fortress 2',
    category: 'games',
    url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/440/library_hero.jpg',
    fallbackUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/440/header.jpg',
    desc: 'Team Shooter',
  },
  {
    id: 'game-stardew',
    name: 'Stardew Valley',
    category: 'games',
    url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/413150/library_hero.jpg',
    fallbackUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/413150/header.jpg',
    desc: 'Farming Sim',
  },
  {
    id: 'game-fallguys',
    name: 'Fall Guys',
    category: 'games',
    url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1097150/library_hero.jpg',
    fallbackUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1097150/header.jpg',
    desc: 'Party Game',
  },
  {
    id: 'game-rocketleague',
    name: 'Rocket League',
    category: 'games',
    url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/252950/library_hero.jpg',
    fallbackUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/252950/header.jpg',
    desc: 'Car Soccer',
  },
  {
    id: 'game-ark',
    name: 'ARK: Survival',
    category: 'games',
    url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/346110/library_hero.jpg',
    fallbackUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/346110/header.jpg',
    desc: 'Dino Survival',
  },
  {
    id: 'game-deadbydaylight',
    name: 'Dead by Daylight',
    category: 'games',
    url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/381210/library_hero.jpg',
    fallbackUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/381210/header.jpg',
    desc: 'Horror Survival',
  },
  {
    id: 'game-sekiro',
    name: 'Sekiro',
    category: 'games',
    url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/814380/library_hero.jpg',
    fallbackUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/814380/header.jpg',
    desc: 'Samurai Action',
  },
  {
    id: 'game-hogwarts',
    name: 'Hogwarts Legacy',
    category: 'games',
    url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/990080/library_hero.jpg',
    fallbackUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/990080/header.jpg',
    desc: 'Wizarding RPG',
  },
  {
    id: 'game-palworld',
    name: 'Palworld',
    category: 'games',
    url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1623730/library_hero.jpg',
    fallbackUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1623730/header.jpg',
    desc: 'Creature Survival',
  },
  {
    id: 'game-baldursgate3',
    name: "Baldur's Gate 3",
    category: 'games',
    url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/library_hero.jpg',
    fallbackUrl: 'https://cdn.akamai.steamstatic.com/steam/apps/1086940/header.jpg',
    desc: 'RPG Epic',
  },
];

// ===== REAL POKÉMON — PokeAPI Official Artwork =====
const BUDPOK_AVATARS: AvatarOption[] = [
  {
    id: 'char-pikachu',
    name: 'Pikachu',
    category: 'budpoks',
    url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=pikachu&size=512',
    isAnimated: true,
    desc: 'Electric Mouse Pokémon',
  },
  {
    id: 'char-charizard',
    name: 'Charizard',
    category: 'budpoks',
    url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/6.png',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=charizard&size=512',
    isAnimated: true,
    desc: 'Fire Dragon Pokémon',
  },
  {
    id: 'char-blastoise',
    name: 'Blastoise',
    category: 'budpoks',
    url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/9.png',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=blastoise&size=512',
    isAnimated: true,
    desc: 'Water Turtle Pokémon',
  },
  {
    id: 'char-venusaur',
    name: 'Venusaur',
    category: 'budpoks',
    url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/3.png',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=venusaur&size=512',
    isAnimated: true,
    desc: 'Grass Flower Pokémon',
  },
  {
    id: 'char-dragonite',
    name: 'Dragonite',
    category: 'budpoks',
    url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/149.png',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=dragonite&size=512',
    isAnimated: true,
    desc: 'Dragon Master Pokémon',
  },
  {
    id: 'char-gyarados',
    name: 'Gyarados',
    category: 'budpoks',
    url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/130.png',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=gyarados&size=512',
    isAnimated: true,
    desc: 'Water Power Pokémon',
  },
  {
    id: 'char-alakazam',
    name: 'Alakazam',
    category: 'budpoks',
    url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/65.png',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=alakazam&size=512',
    isAnimated: true,
    desc: 'Psychic Genius Pokémon',
  },
  {
    id: 'char-arcanine',
    name: 'Arcanine',
    category: 'budpoks',
    url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/59.png',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=arcanine&size=512',
    isAnimated: true,
    desc: 'Fire Hound Pokémon',
  },
  {
    id: 'char-mewtwo',
    name: 'Mewtwo',
    category: 'budpoks',
    url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/150.png',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=mewtwo&size=512',
    isAnimated: true,
    desc: 'Psychic Legend Pokémon',
  },
  {
    id: 'char-lugia',
    name: 'Lugia',
    category: 'budpoks',
    url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/249.png',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=lugia&size=512',
    isAnimated: true,
    desc: 'Water Legendary Pokémon',
  },
  {
    id: 'char-gengar',
    name: 'Gengar',
    category: 'budpoks',
    url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/94.png',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=gengar&size=512',
    isAnimated: true,
    desc: 'Ghost Shadow Pokémon',
  },
  {
    id: 'char-lucario',
    name: 'Lucario',
    category: 'budpoks',
    url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/448.png',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=lucario&size=512',
    isAnimated: true,
    desc: 'Aura Fighter Pokémon',
  },
  {
    id: 'char-greninja',
    name: 'Greninja',
    category: 'budpoks',
    url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/658.png',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=greninja&size=512',
    isAnimated: true,
    desc: 'Ninja Water Pokémon',
  },
  {
    id: 'char-garchomp',
    name: 'Garchomp',
    category: 'budpoks',
    url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/445.png',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=garchomp&size=512',
    isAnimated: true,
    desc: 'Ground Dragon Pokémon',
  },
  {
    id: 'char-rayquaza',
    name: 'Rayquaza',
    category: 'budpoks',
    url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/384.png',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=rayquaza&size=512',
    isAnimated: true,
    desc: 'Sky Legendary Pokémon',
  },
  {
    id: 'char-eevee',
    name: 'Eevee',
    category: 'budpoks',
    url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/133.png',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=eevee&size=512',
    isAnimated: true,
    desc: 'Evolution Pokémon',
  },
];

// ===== TECH LOGOS — SimpleIcons SVG (Vector Quality) with DiceBear Fallback =====
const LOGO_AVATARS: AvatarOption[] = [
  {
    id: 'logo-github',
    name: 'GitHub',
    category: 'logos',
    url: 'https://cdn.simpleicons.org/github/181717',
    fallbackUrl: 'https://api.dicebear.com/7.x/icons/svg?seed=github&size=512',
    desc: 'Code Repository',
  },
  {
    id: 'logo-discord',
    name: 'Discord',
    category: 'logos',
    url: 'https://cdn.simpleicons.org/discord/5865F2',
    fallbackUrl: 'https://api.dicebear.com/7.x/icons/svg?seed=discord&size=512',
    desc: 'Community Chat',
  },
  {
    id: 'logo-spotify',
    name: 'Spotify',
    category: 'logos',
    url: 'https://cdn.simpleicons.org/spotify/1DB954',
    fallbackUrl: 'https://api.dicebear.com/7.x/icons/svg?seed=spotify&size=512',
    desc: 'Music Streaming',
  },
  {
    id: 'logo-figma',
    name: 'Figma',
    category: 'logos',
    url: 'https://cdn.simpleicons.org/figma/F24E1E',
    fallbackUrl: 'https://api.dicebear.com/7.x/icons/svg?seed=figma&size=512',
    desc: 'Design Tool',
  },
  {
    id: 'logo-vscode',
    name: 'VS Code',
    category: 'logos',
    url: 'https://cdn.simpleicons.org/visualstudiocode/007ACC',
    fallbackUrl: 'https://api.dicebear.com/7.x/icons/svg?seed=vscode&size=512',
    desc: 'Code Editor',
  },
  {
    id: 'logo-react',
    name: 'React',
    category: 'logos',
    url: 'https://cdn.simpleicons.org/react/61DAFB',
    fallbackUrl: 'https://api.dicebear.com/7.x/icons/svg?seed=react&size=512',
    desc: 'UI Framework',
  },
  {
    id: 'logo-nodejs',
    name: 'Node.js',
    category: 'logos',
    url: 'https://cdn.simpleicons.org/nodedotjs/339933',
    fallbackUrl: 'https://api.dicebear.com/7.x/icons/svg?seed=nodejs&size=512',
    desc: 'JS Runtime',
  },
  {
    id: 'logo-typescript',
    name: 'TypeScript',
    category: 'logos',
    url: 'https://cdn.simpleicons.org/typescript/3178C6',
    fallbackUrl: 'https://api.dicebear.com/7.x/icons/svg?seed=typescript&size=512',
    desc: 'Type-Safe JS',
  },
  {
    id: 'logo-python',
    name: 'Python',
    category: 'logos',
    url: 'https://cdn.simpleicons.org/python/3776AB',
    fallbackUrl: 'https://api.dicebear.com/7.x/icons/svg?seed=python&size=512',
    desc: 'Programming Language',
  },
  {
    id: 'logo-docker',
    name: 'Docker',
    category: 'logos',
    url: 'https://cdn.simpleicons.org/docker/2496ED',
    fallbackUrl: 'https://api.dicebear.com/7.x/icons/svg?seed=docker&size=512',
    desc: 'Containers',
  },
  {
    id: 'logo-slack',
    name: 'Slack',
    category: 'logos',
    url: 'https://cdn.simpleicons.org/slack/4A154B',
    fallbackUrl: 'https://api.dicebear.com/7.x/icons/svg?seed=slack&size=512',
    desc: 'Team Chat',
  },
  {
    id: 'logo-notion',
    name: 'Notion',
    category: 'logos',
    url: 'https://cdn.simpleicons.org/notion/000000',
    fallbackUrl: 'https://api.dicebear.com/7.x/icons/svg?seed=notion&size=512',
    desc: 'Workspace',
  },
  {
    id: 'logo-openai',
    name: 'OpenAI',
    category: 'logos',
    url: 'https://cdn.simpleicons.org/openai/412991',
    fallbackUrl: 'https://api.dicebear.com/7.x/icons/svg?seed=openai&size=512',
    desc: 'AI Platform',
  },
  {
    id: 'logo-vercel',
    name: 'Vercel',
    category: 'logos',
    url: 'https://cdn.simpleicons.org/vercel/000000',
    fallbackUrl: 'https://api.dicebear.com/7.x/icons/svg?seed=vercel&size=512',
    desc: 'Deployment',
  },
  {
    id: 'logo-tailwind',
    name: 'Tailwind CSS',
    category: 'logos',
    url: 'https://cdn.simpleicons.org/tailwindcss/06B6D4',
    fallbackUrl: 'https://api.dicebear.com/7.x/icons/svg?seed=tailwind&size=512',
    desc: 'CSS Framework',
  },
  {
    id: 'logo-nextjs',
    name: 'Next.js',
    category: 'logos',
    url: 'https://cdn.simpleicons.org/nextdotjs/000000',
    fallbackUrl: 'https://api.dicebear.com/7.x/icons/svg?seed=nextjs&size=512',
    desc: 'React Framework',
  },
];

// ===== EMOJI AVATARS — Apple HD Emojis (High-Resolution 320px) =====
const ANIMATED_AVATARS: AvatarOption[] = [
  {
    id: 'anim-robot',
    name: 'Robot',
    category: 'animated',
    url: 'https://em-content.zobj.net/thumbs/320/apple/354/robot_1f916.png',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=robot&size=512',
    isAnimated: true,
    desc: 'Futuristic Bot',
  },
  {
    id: 'anim-alien',
    name: 'Alien',
    category: 'animated',
    url: 'https://em-content.zobj.net/thumbs/320/apple/354/alien_1f47d.png',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=alien&size=512',
    isAnimated: true,
    desc: 'Extraterrestrial',
  },
  {
    id: 'anim-ninja',
    name: 'Ninja',
    category: 'animated',
    url: 'https://em-content.zobj.net/thumbs/320/apple/354/ninja_1f977.png',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=ninja&size=512',
    isAnimated: true,
    desc: 'Stealthy Warrior',
  },
  {
    id: 'anim-astronaut',
    name: 'Astronaut',
    category: 'animated',
    url: 'https://em-content.zobj.net/thumbs/320/apple/354/astronaut_1f9d1-200d-1f680.png',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=astronaut&size=512',
    isAnimated: true,
    desc: 'Space Explorer',
  },
  {
    id: 'anim-wizard',
    name: 'Wizard',
    category: 'animated',
    url: 'https://em-content.zobj.net/thumbs/320/apple/354/mage_1f9d9.png',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=wizard&size=512',
    isAnimated: true,
    desc: 'Magic Master',
  },
  {
    id: 'anim-ghost',
    name: 'Ghost',
    category: 'animated',
    url: 'https://em-content.zobj.net/thumbs/320/apple/354/ghost_1f47b.png',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=ghost&size=512',
    isAnimated: true,
    desc: 'Spooky Spirit',
  },
  {
    id: 'anim-dragon',
    name: 'Dragon',
    category: 'animated',
    url: 'https://em-content.zobj.net/thumbs/320/apple/354/dragon-face_1f432.png',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=dragon&size=512',
    isAnimated: true,
    desc: 'Mythical Beast',
  },
  {
    id: 'anim-unicorn',
    name: 'Unicorn',
    category: 'animated',
    url: 'https://em-content.zobj.net/thumbs/320/apple/354/unicorn_1f984.png',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=unicorn&size=512',
    isAnimated: true,
    desc: 'Magical Horse',
  },
  {
    id: 'anim-fire',
    name: 'Fire',
    category: 'animated',
    url: 'https://em-content.zobj.net/thumbs/320/apple/354/fire_1f525.png',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=fire&size=512',
    isAnimated: true,
    desc: 'Hot Flame',
  },
  {
    id: 'anim-star',
    name: 'Glowing Star',
    category: 'animated',
    url: 'https://em-content.zobj.net/thumbs/320/apple/354/glowing-star_1f31f.png',
    isAnimated: true,
    desc: 'Shining Star',
  },
  {
    id: 'anim-skull',
    name: 'Skull',
    category: 'animated',
    url: 'https://em-content.zobj.net/thumbs/320/apple/354/skull_1f480.png',
    isAnimated: true,
    desc: 'Dark Vibes',
  },
  {
    id: 'anim-crown',
    name: 'Crown',
    category: 'animated',
    url: 'https://em-content.zobj.net/thumbs/320/apple/354/crown_1f451.png',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=crown&size=512',
    isAnimated: true,
    desc: 'Royalty',
  },
  {
    id: 'anim-clown',
    name: 'Clown',
    category: 'animated',
    url: 'https://em-content.zobj.net/thumbs/320/apple/354/clown-face_1f921.png',
    isAnimated: true,
    desc: 'Funny Face',
  },
  {
    id: 'anim-devil',
    name: 'Devil',
    category: 'animated',
    url: 'https://em-content.zobj.net/thumbs/320/apple/354/smiling-face-with-horns_1f608.png',
    isAnimated: true,
    desc: 'Naughty',
  },
  {
    id: 'anim-cat',
    name: 'Cool Cat',
    category: 'animated',
    url: 'https://em-content.zobj.net/thumbs/320/apple/354/smirking-cat_1f63c.png',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=cat&size=512',
    isAnimated: true,
    desc: 'Feline Vibes',
  },
  {
    id: 'anim-explosion',
    name: 'Explosion',
    category: 'animated',
    url: 'https://em-content.zobj.net/thumbs/320/apple/354/collision_1f4a5.png',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=explosion&size=512',
    isAnimated: true,
    desc: 'Boom',
  },
  {
    id: 'anim-rocket',
    name: 'Rocket',
    category: 'animated',
    url: 'https://em-content.zobj.net/thumbs/320/apple/354/rocket_1f680.png',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=rocket&size=512',
    isAnimated: true,
    desc: 'Space Flight',
  },
  {
    id: 'anim-lightning',
    name: 'Lightning',
    category: 'animated',
    url: 'https://em-content.zobj.net/thumbs/320/apple/354/high-voltage_26a1.png',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=lightning&size=512',
    isAnimated: true,
    desc: 'Electric Power',
  },
];

// ===== AI GENERATED — DiceBear Ultra HD (512px render) =====
const REALISTIC_AVATARS: AvatarOption[] = [
  // Adventurer style (HD)
  {
    id: 'real-adv-alex',
    name: 'Explorer Alex',
    category: 'realistic',
    url: 'https://api.dicebear.com/7.x/adventurer/svg?seed=alex2024&scale=85&size=512',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=alex&size=512',
    isAnimated: true,
    desc: 'Explorer',
  },
  {
    id: 'real-adv-sam',
    name: 'Brave Sam',
    category: 'realistic',
    url: 'https://api.dicebear.com/7.x/adventurer/svg?seed=sam2024&scale=85&size=512',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=sam&size=512',
    isAnimated: true,
    desc: 'Fighter',
  },
  {
    id: 'real-adv-luna',
    name: 'Mage Luna',
    category: 'realistic',
    url: 'https://api.dicebear.com/7.x/adventurer/svg?seed=luna2024&scale=85&size=512',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=luna&size=512',
    isAnimated: true,
    desc: 'Sorcerer',
  },
  {
    id: 'real-adv-max',
    name: 'Rogue Max',
    category: 'realistic',
    url: 'https://api.dicebear.com/7.x/adventurer/svg?seed=max2024&scale=85&size=512',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=max&size=512',
    isAnimated: true,
    desc: 'Shadow',
  },
  // Pixel Art style (HD)
  {
    id: 'real-pix-hero',
    name: 'Pixel Hero',
    category: 'realistic',
    url: 'https://api.dicebear.com/7.x/pixel-art/svg?seed=hero2024&scale=85&size=512',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=hero&size=512',
    isAnimated: true,
    desc: 'Retro 8-bit',
  },
  {
    id: 'real-pix-warrior',
    name: 'Pixel Knight',
    category: 'realistic',
    url: 'https://api.dicebear.com/7.x/pixel-art/svg?seed=warrior2024&scale=85&size=512',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=warrior&size=512',
    isAnimated: true,
    desc: '8-bit Fighter',
  },
  {
    id: 'real-pix-mage',
    name: 'Pixel Wizard',
    category: 'realistic',
    url: 'https://api.dicebear.com/7.x/pixel-art/svg?seed=mage2024&scale=85&size=512',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=mage&size=512',
    isAnimated: true,
    desc: 'Retro Magic',
  },
  {
    id: 'real-pix-rogue',
    name: 'Pixel Rogue',
    category: 'realistic',
    url: 'https://api.dicebear.com/7.x/pixel-art/svg?seed=rogue2024&scale=85&size=512',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=rogue&size=512',
    isAnimated: true,
    desc: 'Retro Stealth',
  },
  // Bottts (Robot) style (HD)
  {
    id: 'real-bot-alpha',
    name: 'Bot Alpha',
    category: 'realistic',
    url: 'https://api.dicebear.com/7.x/bottts/svg?seed=alpha2024&scale=85&size=512',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=alpha&size=512',
    isAnimated: true,
    desc: 'Mechanical',
  },
  {
    id: 'real-bot-beta',
    name: 'Bot Beta',
    category: 'realistic',
    url: 'https://api.dicebear.com/7.x/bottts/svg?seed=beta2024&scale=85&size=512',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=beta&size=512',
    isAnimated: true,
    desc: 'Robot',
  },
  {
    id: 'real-bot-gamma',
    name: 'Bot Gamma',
    category: 'realistic',
    url: 'https://api.dicebear.com/7.x/bottts/svg?seed=gamma2024&scale=85&size=512',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=gamma&size=512',
    isAnimated: true,
    desc: 'Android',
  },
  {
    id: 'real-bot-delta',
    name: 'Bot Delta',
    category: 'realistic',
    url: 'https://api.dicebear.com/7.x/bottts/svg?seed=delta2024&scale=85&size=512',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=delta&size=512',
    isAnimated: true,
    desc: 'Cyborg',
  },
  // Lorelei (Elegant) style (HD)
  {
    id: 'real-lor-pro',
    name: 'Professional',
    category: 'realistic',
    url: 'https://api.dicebear.com/7.x/lorelei/svg?seed=professional2024&scale=85&size=512',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=pro&size=512',
    isAnimated: true,
    desc: 'Business',
  },
  {
    id: 'real-lor-creative',
    name: 'Creative',
    category: 'realistic',
    url: 'https://api.dicebear.com/7.x/lorelei/svg?seed=creative2024&scale=85&size=512',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=creative&size=512',
    isAnimated: true,
    desc: 'Artistic',
  },
  {
    id: 'real-lor-chill',
    name: 'Chill',
    category: 'realistic',
    url: 'https://api.dicebear.com/7.x/lorelei/svg?seed=chill2024&scale=85&size=512',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=chill&size=512',
    isAnimated: true,
    desc: 'Relaxed',
  },
  {
    id: 'real-lor-focus',
    name: 'Focused',
    category: 'realistic',
    url: 'https://api.dicebear.com/7.x/lorelei/svg?seed=focused2024&scale=85&size=512',
    fallbackUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=focus&size=512',
    isAnimated: true,
    desc: 'Determined',
  },
];

// ===== EXPORTS =====

export const ALL_AVATARS: AvatarOption[] = [
  ...GAME_AVATARS,
  ...BUDPOK_AVATARS,
  ...LOGO_AVATARS,
  ...ANIMATED_AVATARS,
  ...REALISTIC_AVATARS,
];

export const getAvatarsByCategory = (category: AvatarCategory): AvatarOption[] => {
  return ALL_AVATARS.filter((avatar) => avatar.category === category);
};

export const getRandomAvatar = (): AvatarOption => {
  return ALL_AVATARS[Math.floor(Math.random() * ALL_AVATARS.length)];
};

export const findAvatarById = (id: string): AvatarOption | undefined => {
  return ALL_AVATARS.find((avatar) => avatar.id === id);
};

export const AVATAR_CATEGORIES = [
  { id: 'games', name: 'Jogos', icon: '🎮', desc: '24 jogos em Ultra HD (1920x620)' },
  { id: 'budpoks', name: 'Pokémon', icon: '⚡', desc: '16 Pokémon oficiais HD (475x475)' },
  { id: 'logos', name: 'Tech', icon: '💻', desc: '16 logos oficiais em vetor SVG' },
  { id: 'animated', name: 'Emojis HD', icon: '✨', desc: '18 emojis Apple 320px HD' },
  { id: 'realistic', name: 'AI Avatars', icon: '👤', desc: '16 avatares AI em 512px HD' },
] as const;
